name: ${name}
artifactId: ${artifactId}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
 
main: ${groupId}.${artifactId}.${mainClass}
mainCommand: ${mainCommand}

commands:
    ${mainCommand}:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this plugin.
    fuck:
        description: Fucking with somebody.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.admin
        permission-message: You are not permitted to fuck this plugin.
    timeout:
        description: Run a command later.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this command.
    multi:
        description: Run multiple commands.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this command.

permissions:
    ${artifactId}.admin:
        description: Gives access to all ${name} administrative commands.
        children:
            ${artifactId}.reload: true
        default: op
    ${artifactId}.reload:
        description: Reloads the plugin.
        default: op
    ${artifactId}.use:
        description: Use this plugin.
        default: true
    ${artifactId}.banned-commands-exempt:
        description: Players with this permission can use banned commands as defined in config.yml
        default: false